data:extend{
  {
    type = "selection-tool",
    name = "tank-squad-command-tool",
    icon = "__tank-squads__/graphics/command-icons/command.png",
    icon_size = 128,
    stack_size = 1,
    flags = {"only-in-cursor", "spawnable", "not-stackable"},
    subgroup = "tool",
    order = "z-tank-squad-c",
    draw_label_for_cursor_render = true,
    select = {
      border_color = {r = 0.2, g = 0.8, b = 0.3},
      cursor_box_type = "entity",
      mode = {"any-entity"},
      entity_filter_mode = "whitelist",
      entity_filters = require("scripts.names").unit_names,
    },
    alt_select = {
      border_color = {r = 0.9, g = 0.3, b = 0.2},
      cursor_box_type = "not-allowed",
      mode = {"any-entity", "nothing"},
    },
  },
  {
    type = "selection-tool",
    name = "tank-squad-ring-centre",
    icon = "__tank-squads__/graphics/command-icons/defense-ring.png",
    icon_size = 128,
    stack_size = 1,
    flags = {"only-in-cursor", "spawnable", "not-stackable"},
    subgroup = "tool",
    order = "z-tank-squad-d",
    select = {border_color = {r = 1, g = 0.8, b = 0.2}, cursor_box_type = "entity", mode = {"nothing"}},
    alt_select = {border_color = {r = 1, g = 0.8, b = 0.2}, cursor_box_type = "entity", mode = {"nothing"}},
  },
  {
    type = "shortcut",
    name = "tank-squad-command-tool",
    action = "spawn-item",
    item_to_spawn = "tank-squad-command-tool",
    icon = "__tank-squads__/graphics/command-icons/command.png",
    icon_size = 128,
    small_icon = "__tank-squads__/graphics/command-icons/command.png",
    small_icon_size = 128,
    technology_to_unlock = "tank-squad-unlock",
  },
  {
    type = "shortcut",
    name = "tank-squad-patrol-mode",
    action = "lua",
    toggleable = true,
    icon = "__tank-squads__/graphics/command-icons/patrol.png",
    icon_size = 128,
    small_icon = "__tank-squads__/graphics/command-icons/patrol.png",
    small_icon_size = 128,
    technology_to_unlock = "tank-squad-unlock",
  },
  {
    type = "shortcut",
    name = "tank-squad-scout-mode",
    action = "lua",
    toggleable = true,
    icon = "__tank-squads__/graphics/command-icons/scout.png",
    icon_size = 128,
    small_icon = "__tank-squads__/graphics/command-icons/scout.png",
    small_icon_size = 128,
    technology_to_unlock = "tank-squad-unlock",
  },
  {
    type = "shortcut",
    name = "tank-squad-escort",
    action = "lua",
    icon = "__tank-squads__/graphics/command-icons/escort.png",
    icon_size = 128,
    small_icon = "__tank-squads__/graphics/command-icons/escort.png",
    small_icon_size = 128,
    technology_to_unlock = "tank-squad-unlock",
  },
  {
    type = "sprite",
    name = "tank-squad-map-locator",
    filename = "__tank-squads__/graphics/command-icons/map.png",
    size = 128,
    flags = {"gui-icon"},
  },
}
