data:extend{
  {
    type = "selection-tool",
    name = "tank-squad-command-tool",
    icon = "__base__/graphics/icons/tank.png",
    stack_size = 1,
    flags = {"only-in-cursor", "spawnable", "not-stackable"},
    subgroup = "tool",
    order = "z-tank-squad-c",
    draw_label_for_cursor_render = true,
    select = {
      border_color = {r = 0.2, g = 0.8, b = 0.3},
      cursor_box_type = "entity",
      mode = {"any-entity"},
      entity_filter_mode = "whitelist",
      entity_filters = require("scripts.names").unit_names,
    },
    alt_select = {
      border_color = {r = 0.9, g = 0.3, b = 0.2},
      cursor_box_type = "not-allowed",
      mode = {"any-entity", "nothing"},
    },
  },
  {
    type = "shortcut",
    name = "tank-squad-command-tool",
    action = "spawn-item",
    item_to_spawn = "tank-squad-command-tool",
    icon = "__base__/graphics/icons/tank.png",
    small_icon = "__base__/graphics/icons/tank.png",
    technology_to_unlock = "tank-squad-unlock",
  },
  {
    type = "shortcut",
    name = "tank-squad-patrol-mode",
    action = "lua",
    toggleable = true,
    icon = "__base__/graphics/icons/radar.png",
    small_icon = "__base__/graphics/icons/radar.png",
    technology_to_unlock = "tank-squad-unlock",
  },
  {
    type = "shortcut",
    name = "tank-squad-scout-mode",
    action = "lua",
    toggleable = true,
    icon = "__base__/graphics/icons/radar.png",
    small_icon = "__base__/graphics/icons/radar.png",
    technology_to_unlock = "tank-squad-unlock",
  },
  {
    type = "shortcut",
    name = "tank-squad-escort",
    action = "lua",
    icon = "__base__/graphics/icons/energy-shield-equipment.png",
    small_icon = "__base__/graphics/icons/energy-shield-equipment.png",
    technology_to_unlock = "tank-squad-unlock",
  },
}
